### ISSUE TITLE
PeerServer stop not working as expected

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethapp#75] opened 2015-10-29 18:19 UTC
after `app.stop()`

```
In [42]: eth.app.services.peermanager.started
Out[42]: False
In [43]: eth.app.services.peermanager.is_stopped
Out[43]: True
In [44]: eth.app.services.peermanager.start()

```

error: [Errno 48] Address already in use: ('0.0.0.0', 29873)
it seems that its failing to stop the streamserver

**Comment by panpilkarz** [comment] 2015-11-10 19:07
I am working on this. 

I can't reproduce sequence app.start() app.stop() app.start() app.stop() ... to fail. 

However I can reproduce bind error if sequence of calls is app.start() app.start(). That results in the situation that app.stop() will never close peermanager socket. Why? On first app.start() peermanger binds to 29873 by self.server instance. On second app.start() peermanger will fail to bind to 29873 however new self.server instance will be initialized and this instance will be used when app.stop() is called. The real self.server is dangling and will be never closed.

This situation should be definitely prevented.

**Comment by panpilkarz** [comment] 2015-11-24 14:53
Fixed. Covered here https://github.com/ethereum/pydevp2p/blob/develop/devp2p/tests/test_full_app.py#L161

**Closed as completed** 2016-02-01 20:12 UTC
