### ISSUE TITLE
pyethapp does not make transactions when run in console mode 

### ISSUE THREAD

**Issue by SethVgr** [ethereum/pyethapp#146] opened 2016-06-15 07:36 UTC
## Checklist
- [done ] installed **pyethapp** inside a **virtualenv**
- [done] ran **pyethapp** with a custom genesis block on a private network:

`pyethapp -c eth.network_id=1337 --data-dir my_testnet -c node.privkey_hex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 -b 'enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@127.0.0.1:30303' -c eth.genesis="my_genesis.json" -m 1000  run --console`
- [done] followed the walk through from [here](https://github.com/ethereum/pyethapp/wiki/The_Console).

namely, the following code (the accounts have been created previously using`pyethapp --data-dir my_testnet account new`):

```
In [6]: acct_service = eth.services.accounts   
In [7]: acct1 = acct_service.accounts[0]
In [8]: acct2 = acct_service.accounts[1]
In [9]: acct1.unlock('')
In [10]: acct2.unlock('')
In [11]:  acct_service.accounts
Out[11]: 
[<Account(address=a741c1ad30bfc3d4f16435e9d32ddb31198ed487, id=None)>,
 <Account(address=bdce83daac449aa98446e1a0d3b9f95eff53cf02, id=None)>]
In [12]: tx = eth.transact('bdce83daac449aa98446e1a0d3b9f95eff53cf02', value=100)
In [13]: eth.find_transaction(tx)
Out[14]: {}
In [15]: INFO:pow.subprocess    nonce found 
INFO:pow.subprocess sending nonce 
In [16]: eth.find_transaction(tx)
Out[17]: {}
```
## System/environment
- OS: debian 8.3 Jessie x64, kernel version 3.16.0-4-amd64, virtual machine, running on VirtualBox, host machine Win7 x64
- python version: 2.7.9
- pyethapp version: 1.2.2/linux2/py2.7.9
- installation method (pip & pypi/git & setup.py): git & setup.py 
## Expected behaviour

**pyethapp** should be able to perform transactions from the first account to the second and also confirm them (since there is only one instance within the private testnet that is also mining). 
## Observed behavior

**pyethapp**  does not mine the transaction; it is never confirmed. Also, it appears that **pyethapp** stops mining if the `--console` flag is set immediately after launch.

**Comment by RomanZacharia** [comment] 2016-06-16 12:25
Such behavior is expected because the block wasn't mined yet. Please reopen the issue if you observe that the transaction didn't get into the mined block.

**Comment by SethVgr** [comment] 2016-06-16 22:05
The issue persists; I've set the difficulty to 0x1 in the genesis block so that mining is done quickly. The block is still not mined.  The version of pyethapp I'm using is:

`pyethapp 1.2.2/linux2/py2.7.9`

Other observations:

-- when run as a bootstrap node with the `--console` flag **pyethapp** also fails to respond to network discovery requests and other nodes connecting to it are "stuck" in a "waiting for bootstrap state".

**Comment by SethVgr** [comment] 2016-07-05 13:48
When running from the terminal and not using the IPython console a block is usually mined in between 30 seconds and a minute. 

Mining stops when the IPython console is launched. Why?

Looking at the CPU usage it's obvious that it's not mining.

**Comment by ulope** [comment] 2016-07-25 17:49
Although this was reported earlier the description in #156 is clearer.

Duplicate of #156

**Closed as completed by ulope** 2016-07-25 17:49 UTC

**Comment by MajjigaDeepak** [comment] 2016-10-18 07:51
I am also facing the same issue, Any one please help me.

After doing transactions the blocks are not generated.

In [23]: eth.transact?
Signature: eth.transact(to, value=0, data='', sender=None, startgas=25000, gaspr                                                                                        ice=60000000000)
Docstring: <no docstring>
File:      ~/Deepak/projects/pyethapp/pyethapp/console_service.py
Type:      instancemethod

In [24]:  tx = eth.transact(to='', data=evm_code, startgas=500000)

In [25]: eth.find_transaction(tx)
Out[25]: {}
