### ISSUE TITLE
AttributeError: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: undefined symbol: EVP_CIPHER_CTX_reset

### ISSUE THREAD

**Issue by tangshuran** [ethereum/pyethapp#199] opened 2017-04-29 09:04 UTC
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: unbuntu 16.10
- python version: 2.7
- pyethapp version: 1.5.0
- installation method (pip & pypi/git & setup.py): pip

## Expected behaviour
(pyethapp) XXX@XXX:~/ethereum/pyethapp$ pyethapp
```
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 11, in <module>
    load_entry_point('pyethapp', 'console_scripts', 'pyethapp')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pyethapp/app.py", line 15, in <module>
    from devp2p.app import BaseApp
  File "/usr/local/lib/python2.7/dist-packages/devp2p/app.py", line 8, in <module>
    from devp2p import crypto
  File "/usr/local/lib/python2.7/dist-packages/devp2p/crypto.py", line 7, in <module>
    import pyelliptic
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/__init__.py", line 43, in <module>
    from .openssl import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/openssl.py", line 310, in <module>
    OpenSSL = _OpenSSL(libname)
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/openssl.py", line 144, in __init__
    self.EVP_CIPHER_CTX_reset = self._lib.EVP_CIPHER_CTX_reset
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: undefined symbol: EVP_CIPHER_CTX_reset
```

What should i do to fix this problem ?

**Comment by ongrid** [comment] 2017-04-30 21:15
Have the same problem. 
Ubuntu 16, Ubuntu 16.04.2 LTS, clean install
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
tried both installed via pip and latest (git develop branch)
`root@eth:~/pyethapp# pyethapp
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 11, in <module>
    load_entry_point('pyethapp', 'console_scripts', 'pyethapp')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/pyethapp/pyethapp/app.py", line 15, in <module>
    from devp2p.app import BaseApp
  File "/usr/local/lib/python2.7/dist-packages/devp2p/app.py", line 8, in <module>
    from devp2p import crypto
  File "/usr/local/lib/python2.7/dist-packages/devp2p/crypto.py", line 7, in <module>
    import pyelliptic
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/__init__.py", line 43, in <module>
    from .openssl import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/openssl.py", line 310, in <module>
    OpenSSL = _OpenSSL(libname)
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/openssl.py", line 144, in __init__
    self.EVP_CIPHER_CTX_reset = self._lib.EVP_CIPHER_CTX_reset
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: undefined symbol: EVP_CIPHER_CTX_reset`

**Comment by scottdonaldau** [comment] 2017-05-01 07:11
Check out my PR to resolve this.

https://github.com/ethereum/pyethapp/pull/198

**Comment by ongrid** [comment] 2017-05-01 09:44
I checked out your PR. Now it installs successfully, but fails on startup with Assertion Error. Is it related to your fix?

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/devp2p/peer.py", line 268, in _run_ingress_message
    self.mux.add_message(imsg)
  File "/usr/local/lib/python2.7/dist-packages/devp2p/muxsession.py", line 51, in _add_message_during_handshake
    rest = session.decode_authentication(msg)
  File "/usr/local/lib/python2.7/dist-packages/devp2p/rlpxcipher.py", line 228, in decode_authentication
    (size, sig, initiator_pubkey, nonce, version) = self.decode_auth_eip8(ciphertext)
  File "/usr/local/lib/python2.7/dist-packages/devp2p/rlpxcipher.py", line 265, in decode_auth_eip8
    assert len(ciphertext) >= size
AssertionError
<Peer('52.183.65.60', 47794) > failed with AssertionError`

**Comment by scottdonaldau** [comment] 2017-05-01 09:49
I do not believe so, the PR simply version locks pyelliptic to 1.5.7 in the requirements file - which is what would have been used prior to 1.5.8 coming out 6 days ago

https://github.com/ethereum/pyethapp/pull/198/files

**Comment by tangshuran** [comment] 2017-05-01 10:53
After adding the line to the requirements and a clean install, everything works fine now.
Thanks ! Problem fixed.

**Comment by gsalgado** [comment] 2017-05-08 07:56
Should be fixed now as the PR in question has been merged

**Comment by charly37** [comment] 2017-05-29 20:15
For those who are not using virtualenv but rather direct install you can fix the error by downgrading the version of pyelliptic with: 
`[root@vps99754 ~]# pip install pyelliptic==1.5.7`
and then verify with:
`pip show pyelliptic`

**Closed as completed** 2017-05-31 04:28 UTC

**Comment by tryjude** [comment] 2017-06-30 02:02
I tried suggestion above to downgrade pyelliptic to 1.5.7 but get a different error now. 

Looks like the best way to go is to clone the repo and use the latest code. I tried to do a pip install but looks like some needed fixes are not in this version.

If anyone is curious, the error I'm getting now (Ubuntu 16) is this:

```
Traceback (most recent call last):
  File "/home/user/Envs/pyethapp/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/home/user/Envs/pyethapp/local/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks
```

**Comment by Marto32** [comment] 2017-07-03 14:51
I'm getting the same error as @tryjude after downgrading via `pip install pyelliptic==1.5.7`

**Comment by AndreMiras** [comment] 2017-07-03 14:57
Yes it's because it's not related, you are getting a different error, hence different ticlet :)
Because pyethereum had some refacto and you need to match both project commit hashes.
I'm currently running the following from my requirements.txt
```
https://github.com/ethereum/pyethereum/archive/0ae64823d1bccba9c8148adb462060cb83c08f06.zip
https://github.com/ethereum/pydevp2p/archive/cc68f6d69fa88ffaac6f8483392c37eb9f19d712.zip
https://github.com/ethereum/pyethapp/archive/409331e88a397ce5276c430aff4a8866d413e45d.zip
```
and it works.
Also you can always check the Travis build log https://travis-ci.org/ethereum/pyethapp/builds, pickup up a green build and try to reproduce the same env.

**Comment by Marto32** [comment] 2017-07-03 15:46
@AndreMiras thanks for the prompt reply. Would you mind sharing your full requirements.txt file?

**Comment by AndreMiras** [comment] 2017-07-03 15:47
Sure, here it is:
https://github.com/AndreMiras/PyWallet/blob/v20170625/requirements/requirements.txt

**Comment by Marto32** [comment] 2017-07-03 16:00
@AndreMiras thanks - still getting that same error - wondering if I should create a new ticket? Here is the dockerfile - it builds successfully but then when I try to run `pyethapp -d /data run --console`:

```
FROM python:2

RUN apt-get update
RUN apt-get install -y \
  git-core \
  build-essential \
  automake \
  pkg-config \
  libtool \
  libffi-dev \
  libgmp-dev \
  python-dev \
  python-pip

RUN pip install pyethapp

# Fix debian's ridiculous gevent-breaking constant removal
# (e.g. https://github.com/hypothesis/h/issues/1704#issuecomment-63893295):
RUN sed -i 's/PROTOCOL_SSLv3/PROTOCOL_SSLv23/g' /usr/local/lib/python2.7/site-packages/gevent/ssl.py

# Update requirements as noted in this conversation:
# https://github.com/ethereum/pyethapp/issues/199#issuecomment-304724903
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN mkdir /data

EXPOSE 8888
EXPOSE 4000
EXPOSE 30303
EXPOSE 30303/udp

VOLUME /data
```

Those 3 zipped repos are included in the requirements file as well as `pyelliptic==1.5.7`

**Comment by AndreMiras** [comment] 2017-07-03 16:04
Well I'm not the pyethapp maintainer, but to me that's a different ticket.
Also nice for making a Dockerfile, but if you create a ticket, alors share your requirements.txt
And last interesting thing would be to have your `pip freeze` output.
